name: "PR Labeler"

on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Configs"
        uses: actions/checkout@v4
        with:
          repository: cssnr/configs
          ref: master
          path: .configs
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            labels/**

      - name: "Debug"
        continue-on-error: true
        run: |
          echo "::group::labels.yaml"
          cat .configs/labels/labels.yaml
          echo "::endgroup::"

          echo "::group::labeler.yaml"
          cat .configs/labels/labeler.yaml
          echo "::endgroup::"

      - name: "Label Creator"
        continue-on-error: true
        uses: cssnr/label-creator-action@master
        with:
          #url: "https://raw.githubusercontent.com/cssnr/label-creator-action/refs/heads/master/.github/labels.yaml"
          file: .configs/labels/labels.yaml

      - name: "Labeler"
        uses: actions/labeler@v6
        with:
          sync-labels: true
          configuration-path: .configs/labels/labeler.yaml
