name: "PR Labeler"

on:
  pull_request_target:

jobs:
  labeler:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Label Creator"
        continue-on-error: true
        uses: cssnr/label-creator-action@master

      - name: "Labeler"
        uses: actions/labeler@v6
        with:
          sync-labels: true
